# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-25 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='field',
            field=models.ManyToManyField(blank=True, to='member.Expertise'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='files',
            field=models.ManyToManyField(blank=True, to='progress.MediaFile'),
        ),
    ]
