# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20161129_1619'),
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='student_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='progress.StudentTask'),
        ),
        migrations.AddField(
            model_name='template',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Member'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='file',
            field=models.ManyToManyField(to='progress.MediaFile'),
        ),
        migrations.AlterField(
            model_name='template',
            name='task',
            field=models.ManyToManyField(to='progress.Task'),
        ),
    ]
