# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_auto_20161225_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='files',
            field=models.ManyToManyField(blank=True, to='progress.MediaFile'),
        ),
        migrations.RemoveField(
            model_name='template',
            name='task'
        ),
        migrations.AddField(
            model_name='template',
            name='task',
            field=models.ManyToManyField(blank=True, through='progress.TemplateTask', to='progress.Task'),
        ),
        migrations.AddField(
            model_name='templatetask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.Task'),
        ),
        migrations.AddField(
            model_name='templatetask',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.Template'),
        ),
    ]
