# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_auto_20161129_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='field',
            field=models.ManyToManyField(to='member.Expertise'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='files',
            field=models.ManyToManyField(to='progress.MediaFile'),
        ),
    ]
