# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 22:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_auto_20161227_0401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='student_task',
        ),
        migrations.AddField(
            model_name='studenttask',
            name='comments',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='progress.Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='type',
            field=models.CharField(choices=[('c', 'komentar'), ('e', 'penjelasan'), ('q', 'pertanyaan')], default='e', max_length=1),
        ),
        migrations.AlterField(
            model_name='studenttask',
            name='status',
            field=models.CharField(choices=[('1', 'belum dikerjakan'), ('2', 'selesai'), ('3', 'sudah dikerjakan'), ('4', 'kerjakan kembali')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='abstract',
            field=models.TextField(blank=True, null=True),
        ),
    ]
