# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_auto_20161227_0542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenttask',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='student_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='progress.StudentTask'),
        ),
    ]
