# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-31 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0006_auto_20161227_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttask',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='studenttask',
            name='duration',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='studenttask',
            name='files',
            field=models.ManyToManyField(blank=True, to='progress.MediaFile'),
        ),
        migrations.AddField(
            model_name='studenttask',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='studenttask',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='studenttask',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='progress.Task'),
        ),
        migrations.AlterField(
            model_name='template',
            name='code',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='member.Member'),
        ),
    ]
