# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 07:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=20, null=True)),
                ('npp', models.CharField(max_length=20, null=True)),
                ('address', models.TextField(null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('level', models.CharField(choices=[('st', 'mahasiswa'), ('sp', 'pembimbing')], default='st', max_length=2)),
                ('status', models.CharField(choices=[('a', 'aktif'), ('b', 'banned'), ('n', 'nonaktif')], default='a', max_length=1)),
                ('expertise', models.ManyToManyField(to='member.Expertise')),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
