# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-25 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('p', 'menunggu'), ('a', 'diterima'), ('r', 'ditolak')], max_length=1)),
                ('propose_date', models.DateTimeField()),
                ('response_date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='expertise',
            field=models.ManyToManyField(blank=True, to='member.Expertise'),
        ),
        migrations.AlterField(
            model_name='member',
            name='level',
            field=models.CharField(choices=[('st', 'mahasiswa'), ('sp', 'pembimbing')], max_length=2),
        ),
        migrations.AlterField(
            model_name='member',
            name='nim',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='npp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Member'),
        ),
        migrations.AddField(
            model_name='studentproposal',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentproposal_student', to='member.Member'),
        ),
        migrations.AddField(
            model_name='studentproposal',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentproposal_supervisor', to='member.Member'),
        ),
    ]
