# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20161129_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='expertise',
            field=models.ManyToManyField(to='member.Expertise'),
        ),
    ]
