# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20161225_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentproposal',
            name='propose_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='studentproposal',
            name='response_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
